Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -27,14 +27,17 @@ jobs:
 
       - name: Print truffleHog version
         run: |
-          echo trufflehog --version
+          trufflehog --version
+
+      - name: Print truffleHog help
+        run: |
+          trufflehog --help
 
       - name: Run truffleHog scan on public repo
         run: |
-          echo "Running truffleHog scan..."
-          trufflehog --entropy=True --json --regex --repo_path https://github.com/pushpalathanelluri/samplerepo.git > trufflehog_public_report.json || { echo 'truffleHog failed'; exit 1; }
+          trufflehog --entropy=True --json --regex https://github.com/pushpalathanelluri/samplerepo.git > trufflehog_public_report.json || { echo 'truffleHog failed'; exit 1; }
 
-      - name: Upload truffleHog report
+      - name: Upload public repo truffleHog report
         uses: actions/upload-artifact@v3
         with:
           name: trufflehog-public-report
